name: Avi Aryan

markdown: kramdown

fullpath: https://aviaryan.in
description: Avi Aryan's personal website
baseurl: 
permalink: /blog/:categories/:title.html
title: Avi Aryan

highlighter: rouge

plugins:
  - jemoji
  - jekyll-mentions

# More
author:
    fullname: Avi Aryan
    twitter: aviaryan123
    github: aviaryan
    facebook: aviaryan123
    image: https://avatars0.githubusercontent.com/u/4047597?v=3&s=256
    google: AviAryan
    gplusid: 110328513842183229282

googleverify: gC8gMLC1UpPDYi2y5KR_9Sq79n4TYMiQM7UcSvtyfms
disqusid: avi-aryan-github
disqusurl: https://aviaryan.in
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
jekyllversion: 3.7.3
